-- Seed enum dropdown values for: project_status, pipeline_stage, importance,
-- project_role, module_type, task_status. Safe to re-run — existing
-- (category, value) pairs are left untouched.
INSERT INTO "enum" (category, value, sort_order) VALUES
('project_status', 'Active', 1),
('project_status', 'Review', 2),
('project_status', 'Complete', 3),
('project_status', 'Archived', 4),
('project_status', 'Stalled', 5),
('pipeline_stage', 'Concept & Ideation', 1),
('pipeline_stage', 'Literature Review', 2),
('pipeline_stage', 'Study Design & Protocol', 3),
('pipeline_stage', 'Ethics and other approvals', 4),
('pipeline_stage', 'Data Collection', 5),
('pipeline_stage', 'Data Analysis', 6),
('pipeline_stage', 'Drafting, writing & revisiting', 7),
('pipeline_stage', 'Under review', 8),
('pipeline_stage', 'Revise & resubmit', 9),
('pipeline_stage', 'Published', 10),
('importance', 'Low', 1),
('importance', 'Medium', 2),
('importance', 'High', 3),
('importance', 'Critical', 4),
('project_role', 'Owner', 1),
('project_role', 'Collaborator', 2),
('project_role', 'Supervisor', 3),
('project_role', 'Lead', 4),
('module_type', 'Research_paper', 1),
('module_type', 'PPT', 2),
('module_type', 'App', 3),
('task_status', 'To_do', 1),
('task_status', 'Underway', 2),
('task_status', 'Waiting', 3),
('task_status', 'Complete', 4)
ON CONFLICT (category, value) DO NOTHING;
