/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return or provision the authenticated user profile */
        get: operations["MeController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user profile */
        patch: operations["MeController_updateMe"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active members of a tenant */
        get: operations["MembershipsController_listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite and email a limited workspace member (owner only)
         * @description Creates a one-time invitation and delivers its acceptance link through Amazon SES. Workspace invitations never create another owner.
         */
        post: operations["MembershipsController_inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/members/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a non-owner workspace member */
        delete: operations["MembershipsController_revokeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview a workspace invitation before sign-in */
        get: operations["InvitationsController_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the invitation for the authenticated email */
        post: operations["InvitationsController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_checkLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_checkReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces available to the authenticated user */
        get: operations["WorkspacesController_list"];
        put?: never;
        /** Create a new workspace owned by the authenticated user */
        post: operations["WorkspacesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's current workspace */
        get: operations["WorkspacesController_getCurrent"];
        /** Switch the authenticated user's current workspace */
        put: operations["WorkspacesController_switchCurrent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dropdown values for a given category */
        get: operations["EnumController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active (non-archived) projects for a workspace */
        get: operations["ProjectsController_list"];
        put?: never;
        /** Create a project */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single project */
        get: operations["ProjectsController_findOne"];
        put?: never;
        post?: never;
        /** Archive a project (auto-deleted after 14 days) */
        delete: operations["ProjectsController_archive"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["ProjectsController_update"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/projects/{projectId}/collaborators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collaborators on a project */
        get: operations["ProjectCollaboratorsController_list"];
        put?: never;
        /** Add a collaborator to a project */
        post: operations["ProjectCollaboratorsController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/projects/{projectId}/collaborators/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a collaborator from a project */
        delete: operations["ProjectCollaboratorsController_remove"];
        options?: never;
        head?: never;
        /** Update a collaborator's role */
        patch: operations["ProjectCollaboratorsController_updateRole"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active modules for a workspace, optionally filtered by project */
        get: operations["ProjectModulesController_list"];
        put?: never;
        /** Create a module, optionally associated with a project */
        post: operations["ProjectModulesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/modules/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single module */
        get: operations["ProjectModulesController_findOne"];
        put?: never;
        post?: never;
        /** Archive a module (auto-deleted after 14 days) */
        delete: operations["ProjectModulesController_archive"];
        options?: never;
        head?: never;
        /** Update a module */
        patch: operations["ProjectModulesController_update"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/modules/{moduleId}/collaborators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collaborators on a module */
        get: operations["ModuleCollaboratorsController_list"];
        put?: never;
        /** Add a collaborator to a module */
        post: operations["ModuleCollaboratorsController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/modules/{moduleId}/collaborators/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a collaborator from a module */
        delete: operations["ModuleCollaboratorsController_remove"];
        options?: never;
        head?: never;
        /** Update a collaborator's role */
        patch: operations["ModuleCollaboratorsController_updateRole"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notes for a workspace, optionally filtered by project */
        get: operations["NotesController_list"];
        put?: never;
        /** Create a note, optionally associated with a project and module */
        post: operations["NotesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single note */
        get: operations["NotesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a note */
        delete: operations["NotesController_remove"];
        options?: never;
        head?: never;
        /** Update a note */
        patch: operations["NotesController_update"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/notes/{noteId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members who can see this shared note */
        get: operations["NoteMembersController_list"];
        put?: never;
        /** Grant a user access to this shared note */
        post: operations["NoteMembersController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/notes/{noteId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a user's access to this shared note */
        delete: operations["NoteMembersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks for a workspace, optionally filtered by project */
        get: operations["TasksController_list"];
        put?: never;
        /** Create a task, optionally associated with a project and module */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single task */
        get: operations["TasksController_findOne"];
        put?: never;
        post?: never;
        /** Delete a task */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        /** Update a task */
        patch: operations["TasksController_update"];
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/tasks/{taskId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members who can see this shared task */
        get: operations["TaskMembersController_list"];
        put?: never;
        /** Grant a user access to this shared task */
        post: operations["TaskMembersController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/tasks/{taskId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a user's access to this shared task */
        delete: operations["TaskMembersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/pipeline-stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipeline stages available to this workspace (base + custom) */
        get: operations["PipelineStagesController_list"];
        put?: never;
        /** Create a custom pipeline stage for this workspace (owner only) */
        post: operations["PipelineStagesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/{tenantId}/pipeline-stages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a custom pipeline stage (owner only) */
        delete: operations["PipelineStagesController_remove"];
        options?: never;
        head?: never;
        /** Rename or reorder a custom pipeline stage (owner only) */
        patch: operations["PipelineStagesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateProfileDto: {
            /** @example Dr Avery Morgan */
            displayName?: string;
            /** @example Research Fellow */
            jobTitle?: string;
            /** @example University of Sydney */
            institution?: string;
            /** @example School of Medical Sciences */
            department?: string;
            /** @example +61 400 000 000 */
            phone?: string;
            /** @example Clinical trials, biomarkers, implementation science */
            researchInterests?: string;
        };
        MembershipResponseDto: {
            id: string;
            tenantId: string;
            userId: string;
            /** Format: email */
            email: string;
            displayName: string;
            /** @enum {string} */
            role: "owner" | "limited_member";
            /** @enum {string} */
            status: "active" | "revoked";
            /** Format: date-time */
            invitedAt: string;
            joinedAt: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateInvitationDto: {
            /** @example colleague@example.com */
            email: string;
        };
        CreateWorkspaceDto: {
            /** @example Acme Research */
            name: string;
        };
        SwitchWorkspaceDto: {
            /** Format: uuid */
            workspaceId: string;
        };
        CreateProjectDto: {
            /** @example Novel Biomarkers in Early-Stage Detection */
            title: string;
            description?: string;
            researchArea?: string;
            /** @example Active */
            status?: string;
            /** @example Concept & Ideation */
            pipelineStage?: string;
            /** @example High */
            importance?: string;
            scheduledFor?: string;
            dueDate?: string;
            totalBudget?: string;
            targetJournals?: string;
        };
        UpdateProjectDto: {
            /** @example Novel Biomarkers in Early-Stage Detection */
            title?: string;
            description?: string;
            researchArea?: string;
            /** @example Active */
            status?: string;
            /** @example Concept & Ideation */
            pipelineStage?: string;
            /** @example High */
            importance?: string;
            scheduledFor?: string;
            dueDate?: string;
            totalBudget?: string;
            targetJournals?: string;
        };
        AddCollaboratorDto: {
            /** @description The internal user ID to add as a collaborator */
            userId: string;
            /** @example Collaborator */
            role: string;
        };
        UpdateRoleDto: {
            /** @example Supervisor */
            role: string;
        };
        CreateModuleDto: {
            /** @example Draft Manuscript */
            title: string;
            description?: string;
            projectId?: string;
            /** @example Research Paper */
            tag?: string;
            /** @example Active */
            status?: string;
            assignedToUserId?: string;
        };
        UpdateModuleDto: {
            /** @example Draft Manuscript */
            title?: string;
            description?: string;
            projectId?: string;
            /** @example Research Paper */
            tag?: string;
            /** @example Active */
            status?: string;
            assignedToUserId?: string;
        };
        CreateNoteDto: {
            /** @example Meeting notes — kickoff */
            title: string;
            content?: string;
            projectId?: string;
            moduleId?: string;
            /** @example Private */
            visibility?: string;
        };
        UpdateNoteDto: {
            /** @example Meeting notes — kickoff */
            title?: string;
            content?: string;
            projectId?: string;
            moduleId?: string;
            /** @example Private */
            visibility?: string;
        };
        AddMemberDto: {
            /** @description The internal user ID to grant access */
            userId: string;
        };
        CreateTaskDto: {
            /** @example Draft introduction section */
            title: string;
            description?: string;
            projectId?: string;
            moduleId?: string;
            /** @example To_do */
            status?: string;
            /** @example High */
            priority?: string;
            /** @example Private */
            visibility?: string;
            workingWith?: string;
            estimatedHours?: string;
            dueDate?: string;
        };
        UpdateTaskDto: {
            /** @example Draft introduction section */
            title?: string;
            description?: string;
            projectId?: string;
            moduleId?: string;
            /** @example To_do */
            status?: string;
            /** @example High */
            priority?: string;
            /** @example Private */
            visibility?: string;
            workingWith?: string;
            estimatedHours?: string;
            dueDate?: string;
        };
        CreatePipelineStageDto: {
            /** @example Peer Review */
            value: string;
            /** @example 5 */
            sortOrder?: number;
        };
        UpdatePipelineStageDto: {
            /** @example Peer Review */
            value?: string;
            /** @example 5 */
            sortOrder?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembershipsController_listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"][];
                };
            };
        };
    };
    MembershipsController_inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email delivery unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembershipsController_revokeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                membershipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"];
                };
            };
        };
    };
    InvitationsController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_checkLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    HealthController_checkReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    WorkspacesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_getCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_switchCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchWorkspaceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EnumController_list: {
        parameters: {
            query: {
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCollaboratorsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCollaboratorsController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollaboratorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCollaboratorsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectCollaboratorsController_updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                projectId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectModulesController_list: {
        parameters: {
            query: {
                projectId: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectModulesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModuleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectModulesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectModulesController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectModulesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModuleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModuleCollaboratorsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModuleCollaboratorsController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollaboratorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModuleCollaboratorsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModuleCollaboratorsController_updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                moduleId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_list: {
        parameters: {
            query?: {
                projectId?: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                noteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NoteMembersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NoteMembersController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                noteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NoteMembersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                noteId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_list: {
        parameters: {
            query?: {
                projectId?: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskMembersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskMembersController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskMembersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                taskId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PipelineStagesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PipelineStagesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePipelineStageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PipelineStagesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PipelineStagesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePipelineStageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
